[package]
name = "bitcask"
version = "0.1.0"
authors = ["Tzu-Chiao Yeh <su3g4284zo6y7@gmail.com>"]
edition = "2018"

[dependencies]
failure = "*"
slog = "*"
slog-term = "*"
slog-async = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

